# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       blts-vcard-xport-perf

# >> macros
# << macros

Summary:    BLTS vcard storage performance test suite
Version:    0.0.1
Release:    0
Group:      Development/Testing
License:    GPLv2
URL:        https://github.com/mer-qa/blts-vcard-xport-perf
Source0:    %{name}-%{version}.tar.gz
Source100:  blts-vcard-xport-perf.yaml
Requires:   qtcontacts-sqlite-qt5
BuildRequires:  pkgconfig(bltscommon)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(Qt5Versit)

%description
This package contains vcard storage performance tests


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/opt/tests/blts-vcard-xport-perf/tests.xml
# >> files
%attr(2755, root, privileged) /opt/tests/blts-vcard-xport-perf/blts-vcard-xport-perf
# << files
